language: elixir
elixir: '1.7.4'
otp_release: '21.0'

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

script:
  - mix format --check-formatted
  - mix test
  - mix coveralls.travis

after_success:
  - mix docs
  - git clone https://github.com/davisp/ghp-import.git
  - ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" doc/
  - echo "Uploaded documentation"
